/datum/voicepack/rousman/get_sound(soundin, modifiers)
	var/used
	switch(soundin)
		if("laugh")
			used = pick('sound/vo/mobs/rousman/ratlaugh1.ogg','sound/vo/mobs/rousman/ratlaugh2.ogg')
		if("aggro")
			used = pick('sound/vo/mobs/rousman/rataggro1.ogg','sound/vo/mobs/rousman/rataggro2.ogg','sound/vo/mobs/rousman/rataggro3.ogg')
		if("deathgurgle")
			used = pick('sound/vo/mobs/rousman/ratdeathgurgle1.ogg','sound/vo/mobs/rousman/ratdeathgurgle2.ogg','sound/vo/mobs/rousman/ratdeathgurgle3.ogg')
		if("breathgasp")
			used = pick('sound/vo/mobs/rousman/ratdeathgurgle1.ogg','sound/vo/mobs/rousman/ratdeathgurgle2.ogg','sound/vo/mobs/rousman/ratdeathgurgle3.ogg')
		if("idle")
			used = pick('sound/vo/mobs/rousman/ratidle1.ogg','sound/vo/mobs/rousman/ratidle2.ogg','sound/vo/mobs/rousman/ratidle3.ogg')
		if("pain")
			used = pick('sound/vo/mobs/rousman/ratpain1.ogg','sound/vo/mobs/rousman/ratpain2.ogg','sound/vo/mobs/rousman/ratpain3.ogg','sound/vo/mobs/rousman/ratpain4.ogg','sound/vo/mobs/rousman/ratpain5.ogg')
		if("paincrit")
			used = pick('sound/vo/mobs/rousman/ratpainscream1.ogg','sound/vo/mobs/rousman/ratpainscream2.ogg','sound/vo/mobs/rousman/ratpainscream3.ogg','sound/vo/mobs/rousman/ratpainscream4.ogg','sound/vo/mobs/rousman/ratpainscream5.ogg')
		if("painscream")
			used = pick('sound/vo/mobs/rousman/ratpainscream1.ogg','sound/vo/mobs/rousman/ratpainscream2.ogg','sound/vo/mobs/rousman/ratpainscream3.ogg','sound/vo/mobs/rousman/ratpainscream4.ogg','sound/vo/mobs/rousman/ratpainscream5.ogg')
		if("scream")
			used = pick('sound/vo/mobs/rousman/ratscream1.ogg','sound/vo/mobs/rousman/ratscream2.ogg')
		if("rage")
			used = pick('sound/vo/mobs/rousman/ratrage1.ogg')
		if("agony")
			used = pick('sound/vo/mobs/rousman/ratagony1.ogg')
		if("drown")
			used = list('sound/vo/male/gen/drown (1).ogg','sound/vo/male/gen/drown (2).ogg','sound/vo/male/gen/drown (3).ogg')
		if("snore")
			used = list('sound/vo/male/gen/snore (1).ogg','sound/vo/male/gen/snore (2).ogg','sound/vo/male/gen/snore (3).ogg','sound/vo/male/gen/snore (4).ogg')
	return used
