name: Suggestion
description: Put in a suggestion
title: "[Suggestion]: "

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to leave a suggestion!

- type: dropdown
  id: category
  attributes:
    label: Categroy
    multiple: true
    description: What sort of suggestion is this?
    options:
      - Balance
      - Map change
      - New Class
      - New Race
      - New Role
      - Alteration to the world/setting
      - Other
  validations:
    required: true

- type: textarea
  id: what
  attributes:
    label: What is the suggestion?
    description: Detail what your suggestion is.
  validations:
    required: true

- type: textarea
  id: why
  attributes:
    label: Why is this suggestion good?
    description: Explain why this suggestion is beneficial for the server.
  validations:
    required: false

- type: input
  id: consult
  attributes:
    label: Staff consulted
    description: If you have consulted a staff developer about this, please put their GitHub username here.
  validations:
    required: false
