#define EXTERNALREPLYCOUNT 2
#define EXTERNAL_PM_USER "IRCKEY"

#define AHELP_CLOSETYPE_CLOSE 0
#define AHELP_CLOSETYPE_REJECT 1
#define AHELP_CLOSETYPE_RESOLVE 2

#define AHELP_CLOSEREASON_NONE 0
#define AHELP_CLOSEREASON_IC 1
#define AHELP_CLOSEREASON_MENTOR 2
