/datum/voicepack/female/abyssariad/get_sound(soundin, modifiers)
	var/used
	switch(modifiers)
		if("old")
			used = getfold(soundin)
		if("young")
			used = getfyoung(soundin)
		if("silenced")
			used = getfsilenced(soundin)
	if(!used)
		switch(soundin)
			if("fatigue")
				used = 'sound/vo/female/abyssariad/fatigue.ogg'
			if("firescream")
				used = list('sound/vo/female/abyssariad/painscream1.ogg','sound/vo/female/abyssariad/painscream2.ogg')
			if("gasp")
				used = list('sound/vo/female/abyssariad/gasp.ogg','sound/vo/female/abyssariad/gasp2.ogg','sound/vo/female/abyssariad/gasp3.ogg','sound/vo/female/abyssariad/gasp4.ogg','sound/vo/female/abyssariad/gasp5.ogg','sound/vo/female/abyssariad/gasp6.ogg')
			if("huh")
				used = list('sound/vo/female/abyssariad/huh.ogg','sound/vo/female/abyssariad/huh1.ogg','sound/vo/female/abyssariad/huh2.ogg')
			if("laugh")
				used = list('sound/vo/female/abyssariad/laugh.ogg','sound/vo/female/abyssariad/laugh1.ogg','sound/vo/female/abyssariad/laugh3.ogg','sound/vo/female/abyssariad/laugh4.ogg','sound/vo/female/abyssariad/laugh5.ogg','sound/vo/female/abyssariad/laugh6.ogg')
			if("groan")
				used = list('sound/vo/female/abyssariad/groan.ogg','sound/vo/female/abyssariad/DISAPPOINTMENT.ogg','sound/vo/female/abyssariad/ah.ogg')
			if("pain")
				used = list('sound/vo/female/abyssariad/pain1.ogg','sound/vo/female/abyssariad/pain2.ogg','sound/vo/female/abyssariad/pain3.ogg','sound/vo/female/abyssariad/pain4.ogg','sound/vo/female/abyssariad/pain5.ogg','sound/vo/female/abyssariad/pain6.ogg')
			if("embed")
				used = list('sound/vo/female/abyssariad/paincrit1.ogg','sound/vo/female/abyssariad/paincrit2.ogg','sound/vo/female/abyssariad/paincrit3.ogg','sound/vo/female/abyssariad/paincrit4.ogg','sound/vo/female/abyssariad/paincrit5.ogg')
			if("paincrit")
				used = list('sound/vo/female/abyssariad/paincrit1.ogg','sound/vo/female/abyssariad/paincrit2.ogg','sound/vo/female/abyssariad/paincrit3.ogg','sound/vo/female/abyssariad/paincrit4.ogg','sound/vo/female/abyssariad/paincrit5.ogg')
			if("painscream")
				used = list('sound/vo/female/abyssariad/painscream1.ogg','sound/vo/female/abyssariad/painscream2.ogg','sound/vo/female/abyssariad/painscream3.ogg')
			if("painmoan")
				used = 'sound/vo/female/abyssariad/screamgasp.ogg'
			if("scream")
				used = list('sound/vo/female/abyssariad/scream1.ogg','sound/vo/female/abyssariad/scream2.ogg','sound/vo/female/abyssariad/scream3.ogg','sound/vo/female/abyssariad/scream4.ogg','sound/vo/female/abyssariad/scream5.ogg','sound/vo/female/abyssariad/scream6.ogg')
			if("throatsing") //need to find a way to put a cooldown on this emote.
				used = list('sound/vo/female/abyssariad/fthroatsing1.ogg','sound/vo/female/abyssariad/fthroatsing2.ogg','sound/vo/female/abyssariad/fthroatsing3.ogg','sound/vo/female/abyssariad/fthroatsing4.ogg')
			if("breathgasp")
				used = list('sound/vo/female/abyssariad/deathgasp.ogg','sound/vo/female/abyssariad/deathgasp2.ogg','sound/vo/female/abyssariad/deathgasp3.ogg')
			if("chuckle")
				used = list('sound/vo/female/abyssariad/chuckle3.ogg','sound/vo/female/abyssariad/chuckle4.ogg','sound/vo/female/abyssariad/chuckle5.ogg','sound/vo/female/abyssariad/chuckle6.ogg')
			if("giggle")
				used = list('sound/vo/female/abyssariad/chuckle1.ogg','sound/vo/female/abyssariad/chuckle2.ogg')
			if("grumble") //need to find a way to make a bigger cooldown on this one. This emote is long.
				if(prob(5))
					used = 'sound/vo/female/abyssariad/wawawa.ogg' //I do not fear being murdered during my sleep.
				else
					used = list('sound/vo/female/abyssariad/grumble1.ogg','sound/vo/female/abyssariad/grumble2.ogg','sound/vo/female/abyssariad/grumble3.ogg','sound/vo/female/abyssariad/grumble4.ogg')
			if("jump")
				used = list('sound/vo/female/abyssariad/jump1.ogg','sound/vo/female/abyssariad/jump2.ogg','sound/vo/female/abyssariad/jump3.ogg')
			if("leap")
				used = list('sound/vo/female/abyssariad/jump4.ogg','sound/vo/female/abyssariad/jump5.ogg','sound/vo/female/abyssariad/jump6.ogg')
			if("rage")
				used = list('sound/vo/female/abyssariad/angry1.ogg','sound/vo/female/abyssariad/angry2.ogg')
			if("sexmoanlight")
				used = list('sound/vo/female/abyssariad/smoan1.ogg','sound/vo/female/abyssariad/smoan2.ogg','sound/vo/female/abyssariad/smoan3.ogg','sound/vo/female/abyssariad/smoan4.ogg','sound/vo/female/abyssariad/smoan5.ogg','sound/vo/female/abyssariad/smoan6.ogg','sound/vo/female/abyssariad/smoan7.ogg','sound/vo/female/abyssariad/smoan8.ogg','sound/vo/female/abyssariad/smoan9.ogg','sound/vo/female/abyssariad/smoan10.ogg')
			if("sexmoanhvy")
				used = list('sound/vo/female/abyssariad/moanheavy1.ogg','sound/vo/female/abyssariad/moanheavy2.ogg','sound/vo/female/abyssariad/moanheavy3.ogg','sound/vo/female/abyssariad/moanheavy4.ogg','sound/vo/female/abyssariad/moanheavy5.ogg','sound/vo/female/abyssariad/moanheavy6.ogg','sound/vo/female/abyssariad/moanheavy7.ogg','sound/vo/female/abyssariad/moanheavy8.ogg','sound/vo/female/abyssariad/moanheavy9.ogg','sound/vo/female/abyssariad/moanheavy10.ogg','sound/vo/female/abyssariad/moanheavy11.ogg','sound/vo/female/abyssariad/moanheavy12.ogg','sound/vo/female/abyssariad/moanheavy13.ogg','sound/vo/female/abyssariad/moanheavy14.ogg','sound/vo/female/abyssariad/moanheavy15.ogg','sound/vo/female/abyssariad/moanheavy16.ogg','sound/vo/female/abyssariad/moanheavy17.ogg','sound/vo/female/abyssariad/moanheavy18.ogg','sound/vo/female/abyssariad/moanheavy19.ogg','sound/vo/female/abyssariad/moanheavy20.ogg')
			if("moan")
				used = list('sound/vo/female/abyssariad/moan1.ogg','sound/vo/female/abyssariad/moan2.ogg','sound/vo/female/abyssariad/moan4.ogg','sound/vo/female/abyssariad/moan5.ogg')
			if("birdcall")
				used = list('sound/vo/female/abyssariad/moan1.ogg','sound/vo/female/abyssariad/moan2.ogg','sound/vo/female/abyssariad/moan4.ogg','sound/vo/female/abyssariad/moan5.ogg')
	if(!used) //we haven't found a racial specific sound so use generic
		used = ..(soundin)
	return used
